name = "projectblox"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "projectblox-db"
database_id = "59442a06-711c-48dc-b14f-cbca14bfd998"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "projectblox-assets"

[env.production]
vars = { ENVIRONMENT = "production" }
